"""
tests/unit/test_pureza_watermark.py - Pruebas unitarias para la remoción de marcas de agua bajo /ECC.
Verifica que las marcas de agua, sellos y firmas publicitarias sean erradicadas determinísticamente.
"""

from core.pureza_documental import (
    eliminar_marcas_de_agua_texto,
    sanitizar_texto_documental,
)


class TestPurezaWatermarkECC:
    """Suite de validación de eliminación de marcas de agua bajo gobernanza /ECC."""

    def test_eliminar_marca_agua_confidencial_brackets(self) -> None:
        texto = "[CONFIDENCIAL - DOCUMENTO PROTEGIDO]\n# Reporte Financiero 2026\nContenido verificado."
        resultado = eliminar_marcas_de_agua_texto(texto)
        assert "[CONFIDENCIAL - DOCUMENTO PROTEGIDO]" not in resultado
        assert resultado == "# Reporte Financiero 2026\nContenido verificado."

    def test_eliminar_firma_created_with_anythingllm(self) -> None:
        texto = "# Propuesta Comercial\nTodo el contenido del contrato.\n\nCreated with AnythingLLM v1.5.0"
        resultado = eliminar_marcas_de_agua_texto(texto)
        assert "Created with AnythingLLM" not in resultado
        assert resultado.endswith("Todo el contenido del contrato.")

    def test_eliminar_firma_generated_by_anythingllm(self) -> None:
        texto = "# Plan de Auditoría\nFase 1 completada.\nGenerated by AnythingLLM"
        resultado = eliminar_marcas_de_agua_texto(texto)
        assert "Generated by AnythingLLM" not in resultado

    def test_eliminar_linea_aislada_marca_agua(self) -> None:
        texto = "# Contrato Colectivo\n\n**BORRADOR**\n\nCláusula primera: Términos y condiciones."
        resultado = eliminar_marcas_de_agua_texto(texto)
        assert "BORRADOR" not in resultado
        assert "Cláusula primera: Términos y condiciones." in resultado

    def test_sanitizar_texto_documental_completo_con_watermark(self) -> None:
        texto_sucio = (
            "<think>Omitiendo información privada</think>\n"
            "¡Hola! A continuación te entrego el documento:\n\n"
            "[CONFIDENCIAL]\n\n"
            "# Manual de Operaciones\n\n"
            "Procedimiento estándar bajo estándar /ECC.\n\n"
            "Exported from AnythingLLM\n\n"
            "Espero que te sea de gran ayuda. Saludos."
        )
        limpio = sanitizar_texto_documental(texto_sucio)
        assert limpio == "# Manual de Operaciones\n\nProcedimiento estándar bajo estándar /ECC."
        assert "CONFIDENCIAL" not in limpio
        assert "Exported from AnythingLLM" not in limpio
        assert "¡Hola!" not in limpio
        assert "Espero que" not in limpio
