"""
core/pureza_documental.py - Sanitizador y Guardarraíl Determinista de Pureza Documental.
Elimina completamente cualquier residuo conversacional, notas explicativas de la IA,
disculpas, preámbulos y epílogos coloquiales para garantizar que los documentos
compilados contengan 100% contenido legítimo y 0% charla ("Zero-Chatter Protocol").
Bajo gobernanza /ECC y estándares de ciberseguridad por diseño.
"""

import re
from typing import Dict, List, Tuple
from logs import logger


# Patrones regex de apertura conversacional que deben ser eliminados de raíz
PATRONES_PREAMBULO: List[re.Pattern] = [
    re.compile(r"^[\s\S]*?(?=(?:^#{1,3}\s+[^\n]+))", re.MULTILINE),  # Texto previo al primer encabezado Markdown
]

PATRONES_FRASES_CHATTER_INICIO: List[re.Pattern] = [
    re.compile(r"^(?:¡?Hola!?|Saludos|Estimad[oa]|Buenos días|Buenas tardes)[^\n]*\n*", re.IGNORECASE),
    re.compile(r"^(?:Voy a corregir|A continuación|Aquí (?:tienes|está|presento)|Te presento|He corregido|Procedo a)[^\n]*\n*", re.IGNORECASE),
    re.compile(r"^(?:Detalles técnicos del procesamiento|Resumen de cambios|Nota del asistente|Notas de corrección)[^\n]*\n*", re.IGNORECASE),
    re.compile(r"^(?:A continuación se muestra|Versión corregida|Documento corregido)[^\n]*:\s*\n*", re.IGNORECASE),
    re.compile(r"^(?:Este|El presente) resumen proporciona[^\n]*\n*", re.IGNORECASE),
]

PATRONES_FRASES_CHATTER_FINAL: List[re.Pattern] = [
    re.compile(r"\n*(?:Si necesitas|Espero que|No dudes en|Quedo a tu disposición|Cualquier duda|¿Hay algo más|Si tienes alguna)[^\n]*$", re.IGNORECASE),
    re.compile(r"\n*(?:El documento ha sido convertido|Si requieres cambios adicionales|Saludos cordiales|Atentamente)[^\n]*$", re.IGNORECASE),
    re.compile(r"\n*---+\s*\n*(?:Detalles técnicos|Documento reconstruido|El documento ha sido)[^\n]*$", re.IGNORECASE),
]

# Patrones regex de marcas de agua textuales y firmas de software (/ECC)
PATRONES_MARCAS_AGUA_TEXTO: List[re.Pattern] = [
    re.compile(r"\[\s*(?:CONFIDENCIAL|BORRADOR|DRAFT|SAMPLE|COPIA|PROTEGIDO|DOCUMENTO PROTEGIDO)[^\]]*\]", re.IGNORECASE),
    re.compile(r"(?:Created with|Generated by|Exported from)\s+AnythingLLM[^\n]*", re.IGNORECASE),
    re.compile(r"(?:Creado con|Generado por|Exportado desde)\s+AnythingLLM[^\n]*", re.IGNORECASE),
]

# Patrones regex de simulación de generación de archivos, introducciones y notas espurias agregadas por la IA
PATRONES_METATEXTO_ELIMINAR: List[re.Pattern] = [
    re.compile(r"(?:^|\n)---+\s*\n*(?:Este|El presente) resumen proporciona[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)(?:Este|El presente) resumen proporciona[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)---+\s*\n*Nota:\s*Los campos \[?pendiente\]?[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)Nota:\s*Los campos \[?pendiente\]?[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)---+\s*\n*Generando archivo (?:PDF|Word|DOCX|ODT|documento)[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)Generando archivo (?:PDF|Word|DOCX|ODT|documento)[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)\[\s*El archivo (?:PDF|Word|DOCX|ODT|documento) se generará automáticamente[^\n\]]*\]", re.IGNORECASE),
    re.compile(r"(?:^|\n)---+\s*\n*Archivo (?:PDF|Word|DOCX|ODT|documento) Generado:?[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)Archivo (?:PDF|Word|DOCX|ODT|documento) Generado:?[\s\S]*?(?=\n#|\n---|\n\n|$)", re.IGNORECASE),
    re.compile(r"(?:^|\n)\[\s*Archivo (?:PDF|Word|DOCX|ODT|documento) adjunto[^\n\]]*\]", re.IGNORECASE),
    re.compile(r"(?:^|\n)---+\s*\n*$", re.MULTILINE),
]


def eliminar_chatter_generacion_y_metatextos(texto: str) -> str:
    """
    Elimina bloques espurios agregados por la IA donde simula la generación de archivos,
    agrega introducciones tipo 'Este resumen proporciona...', notas de campos pendientes, etc.
    """
    if not texto:
        return ""
    limpio = texto
    for patron in PATRONES_METATEXTO_ELIMINAR:
        limpio = patron.sub("", limpio)
    limpio = re.sub(r"\n{3,}", "\n\n", limpio)
    return limpio.strip()


def eliminar_etiquetas_razonamiento(texto: str) -> str:
    """Elimina etiquetas de razonamiento como <think>...</think> o [THINK]...[/THINK]."""
    texto_sin_think = re.sub(r"<think>[\s\S]*?</think>", "", texto, flags=re.DOTALL)
    texto_sin_think = re.sub(r"\[THINK\][\s\S]*?\[/THINK\]", "", texto_sin_think, flags=re.DOTALL)
    return texto_sin_think.strip()


def limpiar_preambulos_conversacionales(texto: str) -> str:
    """
    Elimina preámbulos tipo 'Voy a corregir el documento', 'Aquí tienes...',
    o metatextos técnicos generados por el LLM antes de comenzar el documento.
    """
    lineas = texto.splitlines()
    if not lineas:
        return ""

    # Si el texto contiene encabezados Markdown (# Título), buscar el primer encabezado legítimo
    primer_header_idx = -1
    for idx, linea in enumerate(lineas):
        linea_str = linea.strip()
        # Ignorar si es un encabezado falso de chatter tipo "### Detalles Técnicos del Procesamiento" o "### Documento Reconstruido"
        if re.match(r"^#{1,3}\s+(?:Detalles Técnicos|Documento Reconstruido|Notas de Corrección|Resumen de Cambios)", linea_str, re.IGNORECASE):
            continue
        if re.match(r"^#{1,3}\s+", linea_str):
            primer_header_idx = idx
            break

    if primer_header_idx > 0:
        # Verificar si las líneas previas eran chatter conversacional o resúmenes añadidos
        lineas_previas = "\n".join(lineas[:primer_header_idx])
        palabras_chatter = [
            "detalles técnicos", "procesamiento", "este resumen", "el presente resumen",
            "resumen proporciona", "visión clara", "nota:", "generando archivo",
            "voy a corregir", "a continuación", "aquí tienes", "he corregido"
        ]
        es_chatter_previo = any(
            p.search(lineas_previas) for p in PATRONES_FRASES_CHATTER_INICIO
        ) or any(palabra in lineas_previas.lower() for palabra in palabras_chatter)

        if es_chatter_previo:
            logger.info(f"Zero-Chatter: Se recortaron {primer_header_idx} líneas de preámbulo conversacional.")
            lineas = lineas[primer_header_idx:]

    texto_reducido = "\n".join(lineas).strip()

    # Limpiar líneas iniciales individuales de saludo/intención
    cambio = True
    while cambio and texto_reducido:
        cambio = False
        for patron in PATRONES_FRASES_CHATTER_INICIO:
            match = patron.match(texto_reducido)
            if match:
                texto_reducido = texto_reducido[match.end():].lstrip()
                cambio = True
                break

    return texto_reducido.strip()


def limpiar_epilogos_conversacionales(texto: str) -> str:
    """
    Elimina despedidas o notas al pie añadidas por el LLM
    como 'Si necesitas más detalles...', 'Espero que te sirva', etc.
    """
    lineas = texto.splitlines()
    if not lineas:
        return ""

    # Revisar desde el final hacia arriba líneas de chatter
    while lineas:
        ultima_linea = lineas[-1].strip()
        if not ultima_linea:
            lineas.pop()
            continue

        es_chatter = any(p.search(ultima_linea) for p in PATRONES_FRASES_CHATTER_FINAL)
        # Bloques de separador con notas de cierre
        if ultima_linea in ("---", "***") and len(lineas) > 1 and any(p.search(lineas[-2]) for p in PATRONES_FRASES_CHATTER_FINAL):
            es_chatter = True

        if es_chatter:
            logger.info(f"Zero-Chatter: Se recortó línea de epílogo conversacional: '{ultima_linea}'")
            lineas.pop()
        else:
            break

    return "\n".join(lineas).strip()


def eliminar_marcas_de_agua_texto(texto: str) -> str:
    """
    Elimina leyendas de marcas de agua textuales, sellos y firmas publicitarias
    bajo gobernanza /ECC para garantizar pureza documental absoluta.
    """
    if not texto:
        return ""
    texto_limpio = texto
    for patron in PATRONES_MARCAS_AGUA_TEXTO:
        texto_limpio = patron.sub("", texto_limpio)

    # Filtrar líneas que contengan únicamente palabras clave de marca de agua o sellos
    lineas_filtradas = []
    palabras_clave_linea = {
        "confidencial", "borrador", "draft", "sample", "copia",
        "copia no controlada", "documento protegido"
    }
    for linea in texto_limpio.splitlines():
        linea_strip = linea.strip().strip("*_#[]- ").lower()
        if linea_strip in palabras_clave_linea:
            logger.info(f"Zero-Watermark (/ECC): Se eliminó línea de marca de agua: '{linea.strip()}'")
            continue
        lineas_filtradas.append(linea)

    return "\n".join(lineas_filtradas).strip()


def sanitizar_texto_documental(texto_crudo: str) -> str:
    """
    Función principal del Protocolo de Pureza Documental (Zero-Chatter & Zero-Watermark).
    Toma la salida textual de una inferencia o documento y asegura que esté 100% limpia
    de chatter, razonamiento interno, marcas de agua, simulaciones de generación de archivos
    o añadidos artificiales antes de ser reconstruida.
    """
    if not texto_crudo or not texto_crudo.strip():
        return ""

    # 1. Eliminar etiquetas <think>
    texto_sin_pensamiento = eliminar_etiquetas_razonamiento(texto_crudo)

    # 2. Eliminar marcas de agua y firmas residuales (/ECC)
    texto_sin_marcas = eliminar_marcas_de_agua_texto(texto_sin_pensamiento)

    # 3. Eliminar chatter de generación de archivos y metatextos espurios
    texto_sin_metatexto = eliminar_chatter_generacion_y_metatextos(texto_sin_marcas)

    # 4. Eliminar preámbulos conversacionales
    texto_sin_preambulo = limpiar_preambulos_conversacionales(texto_sin_metatexto)

    # 5. Eliminar epílogos conversacionales
    texto_sanitizado = limpiar_epilogos_conversacionales(texto_sin_preambulo)

    return texto_sanitizado.strip()


def calcular_indice_pureza(texto_original: str, texto_sanitizado: str) -> float:
    """
    Calcula un score de 0.0 a 100.0% indicando el ratio de pureza y retención.
    """
    len_orig = len(texto_original.strip())
    len_san = len(texto_sanitizado.strip())
    if len_orig == 0:
        return 100.0
    return round((len_san / len_orig) * 100.0, 2)


# Patrones regex de rechazo e incapacidad conversacional del modelo
PATRONES_RECHAZO: List[re.Pattern] = [
    re.compile(r"(?:lo siento|disculpa|perdón),?\s*pero\s*(?:como|no puedo|no tengo|no soy|actualmente)", re.IGNORECASE),
    re.compile(r"no\s+(?:tengo|poseo)\s+(?:la\s+)?capacidad\s+de\s+(?:analizar|corregir|procesar|revisar|editar|ver|abrir|leer)", re.IGNORECASE),
    re.compile(r"no\s+puedo\s+(?:analizar|corregir|procesar|revisar|editar|ver|abrir|leer|adjuntar)\s+(?:archivos?|documentos?|el\s+documento|este\s+documento|formatos?)", re.IGNORECASE),
    re.compile(r"como\s+(?:asistente|modelo)\s*(?:de\s+ia|de\s+inteligencia\s+artificial|de\s+lenguaje)[^.\n]*no\s+(?:tengo|puedo|poseo)", re.IGNORECASE),
    re.compile(r"por\s+favor,?\s+proporciona\s+(?:el|los)?\s*(?:contenido|texto|datos)\s*del\s*documento", re.IGNORECASE),
    re.compile(r"i\s*(?:am\s*sorry|apologize),?\s*but\s*as\s*an\s*ai", re.IGNORECASE),
    re.compile(r"i\s*(?:cannot|can't|do\s*not\s*have\s*the\s*ability\s*to)\s*(?:analyze|process|correct|edit|view|read)", re.IGNORECASE),
    re.compile(r"as\s*an\s*ai\s*(?:assistant|language\s*model)[^.\n]*(?:cannot|can't)", re.IGNORECASE),
]


def es_respuesta_de_rechazo(texto: str) -> bool:
    """
    Detecta si la respuesta generada por el LLM es un rechazo, declaración de
    incapacidad o disculpa conversacional en lugar de contenido procesado.
    Evita que mensajes de rechazo sean exportados como documentos válidos.
    """
    if not texto or not texto.strip():
        return True

    texto_lower = texto.lower().strip()

    es_rechazo = any(p.search(texto_lower) for p in PATRONES_RECHAZO)
    if es_rechazo:
        # Si el texto es breve (< 120 palabras) y contiene una frase de rechazo, es un rechazo seguro
        num_palabras = len(texto.split())
        if num_palabras < 120:
            return True

        # Si el texto comienza con una frase de rechazo en las primeras 3 líneas y no contiene estructura documental
        primeras_lineas = "\n".join(texto_lower.splitlines()[:3])
        if any(p.search(primeras_lineas) for p in PATRONES_RECHAZO):
            headers = re.findall(r"^#{1,3}\s+", texto, re.MULTILINE)
            if len(headers) < 2:
                return True

    return False


# Mapeo determinista de mojibake UTF-8 / Latin-1 / CP1252 y acentos graves espurios
MOJIBAKE_MAP: Dict[str, str] = {
    # Minúsculas con tildes y caracteres especiales
    "Ã¡": "á", "Ã©": "é", "Ã­": "í", "Ã³": "ó", "Ãº": "ú", "Ã±": "ñ", "Ã¼": "ü",
    "Ã\xad": "í", "\xc3\xac": "í", "\xc3\u0161": "Ú", "\xc3\ufffd": "Ú",
    # Mayúsculas con tildes
    "Ã ": "Á", "Ã‰": "É", "Ã ": "Í", "Ã“": "Ó", "Ãš": "Ú", "Ã‘": "Ñ", "Ãœ": "Ü",
    # Signos especiales
    "Â¿": "¿", "Â¡": "¡", "Âº": "º", "Âª": "ª", "Â«": "«", "Â»": "»",
    "â€œ": '"', "â€ ": '"', "â€˜": "'", "â€™": "'", "â€”": "—", "â€“": "–", "â€¦": "...",
    # Variaciones corruptas frecuentes en documentos de prueba y OCR
    "guÃ¬a": "guía", "guÃ¬": "guí", "guìa": "guía",
    "tÃ©cniCa": "técnica", "tÃ©cnica": "técnica", "TÃ©cNica": "Técnica",
    "DOcumEntaciÃ³n": "Documentación", "docuemnto": "documento",
    "AutenticaciÃ³n": "Autenticación", "autenticaciÃ³n": "autenticación",
    "InstAlaciÃ³n": "Instalación", "instalaciÃ³n": "instalación",
    "conexiÃ³n": "conexión", "bÃ¡sico": "básico",
    "contraseÃ±a": "contraseña", "contraseÃ±as": "contraseñas",
    "MÃ³dulos": "Módulos", "mÃ³dulos": "módulos",
    "disponÃ¬bles": "disponibles", "disponìbles": "disponibles",
    "usuarÃ¬os": "usuarios", "usuarÃ¬o": "usuario", "usuarìos": "usuarios", "usuarìo": "usuario",
    "TroubleshootÃ¬ng": "Troubleshooting", "troubleshootÃ¬ng": "troubleshooting",
    "soluciones mÃ¡gicas": "solución de incidencias", "mÃ¡gicas": "mágicas",
    "TelÃ©fono": "Teléfono", "telÃ©fono": "teléfono",
    "DirecciÃ³n": "Dirección", "direcciÃ³n": "dirección",
    "estÃ¡": "está", "Ãšsalo": "Úsalo", "Ãºsalo": "úsalo",
    "CÃ³digo": "Código", "cÃ³digo": "código",
    "parÃ©ntesis": "paréntesis", "tÃ©rminos": "términos",
    "aquÃ¬": "aquí", "aquì": "aquí",
    "automÃ¡ticamente": "automáticamente", "VersiÃ³n": "Versión", "versiÃ³n": "versión",
    "Ãšltima": "Última", "Ãºltima": "última", "Ãltima": "Última",
    "perÃ²": "pero", "però": "pero",
    "asÃ¬": "así", "asì": "así", "asÃ¨": "así", "asè": "así",
    "sÃ¬": "sí", "sì": "sí",
    "aÃºn": "aún",
}


def normalizar_mojibake(texto: str) -> str:
    """
    Normaliza y repara secuencias de mojibake UTF-8 corruptas y elimina
    acentos graves espurios (è, ò, à, ì, ù) que inducen a los LLMs a desviarse
    hacia el catalán o el italiano. Garantiza español técnico puro libre de ruido.
    """
    if not texto:
        return ""

    texto_reparado = texto
    # 1. Reemplazos directos del diccionario de mojibake
    for patron, reemplazo in MOJIBAKE_MAP.items():
        if patron in texto_reparado:
            texto_reparado = texto_reparado.replace(patron, reemplazo)

    # 2. Corrección general de acentos graves a agudos (en español no existen acentos graves)
    # Evita que el LLM confunda texto en español con catalán o italiano
    reemplazos_graves = {
        "à": "á", "è": "é", "ì": "í", "ò": "ó", "ù": "ú",
        "À": "Á", "È": "É", "Ì": "Í", "Ò": "Ó", "Ù": "Ú"
    }
    for grave, agudo in reemplazos_graves.items():
        if grave in texto_reparado:
            texto_reparado = texto_reparado.replace(grave, agudo)

    # 3. Corrección de palabras corruptas o catalanismos comunes inducidos por OCR/ruido
    reemplazos_catalanismos = {
        r"\bperò\b": "pero",
        r"\bamb\b": "con",
        r"\baquest\b": "este",
        r"\baquesta\b": "esta",
        r"\bté\b": "tiene",
        r"\btens de\b": "debes",
        r"\busuaris\b": "usuarios",
        r"\binstal·lació\b": "instalación",
        r"\binstalacio\b": "instalación",
        r"\bconnexió\b": "conexión",
        r"\bconnexio\b": "conexión",
        r"\bdescarrega\b": "descarga",
        r"\bexecuta\b": "ejecuta",
        r"\bcompartís\b": "compartas",
        r"\brevisió\b": "revisión",
        r"\bllicència\b": "licencia",
        r"\bseguretat\b": "seguridad",
        r"\bllora un peu\b": "documentar el fallo y aplicar rollback",
        r"\bllora un poco\b": "documentar el fallo y aplicar rollback",
        r"\breza per que funcioni\b": "verificar dependencias y logs del servicio",
        r"\breza para que funcione\b": "verificar dependencias y logs del servicio",
    }
    for patron_regex, sub_val in reemplazos_catalanismos.items():
        texto_reparado = re.sub(patron_regex, sub_val, texto_reparado, flags=re.IGNORECASE)

    return texto_reparado


